"""Word → sentence joiner: table-driven unit tests plus a golden fixture of
real tiny.en words (first 600 s of TAL episode 01-646, regenerated by
scripts/make_joiner_fixture.py)."""

from __future__ import annotations

import gzip
import json
import unittest
from pathlib import Path

from noadcast.transcribe.codec import decode_segments, decode_words, encode_segments, encode_words
from noadcast.transcribe.joiner import (
    JoinerParams,
    derive_silences,
    is_sentence_end,
    join_words,
    repeat_runs,
)
from noadcast.transcribe.protocol import AsrSegmentMeta, SilenceRegion, Word

FIXTURE = Path(__file__).parent / "fixtures" / "words_01-646_first600s.json.gz"


def load_fixture() -> tuple[dict, list[Word], list[AsrSegmentMeta]]:
    fixture = json.loads(gzip.decompress(FIXTURE.read_bytes()))
    words = [Word(**dict(zip(fixture["word_fields"], row))) for row in fixture["words"]]
    segments = [AsrSegmentMeta(**dict(zip(fixture["segment_fields"], row))) for row in fixture["segments"]]
    return fixture, words, segments


def lay(*items: str | float, start: float = 0.0, dur: float = 0.30, gap: float = 0.02,
        p: float = 0.95, segment: int = 0) -> list[Word]:
    """Words laid back to back, ``dur`` long and ``gap`` apart. Items are raw
    tokens (leading space included); a float item sets the pause before the
    next token instead."""
    words: list[Word] = []
    pause: float | None = None
    t = start
    for item in items:
        if isinstance(item, float):
            pause = item
            continue
        if words:
            t = words[-1].end + (gap if pause is None else pause)
        words.append(Word(round(t, 2), round(t + dur, 2), item, p, segment))
        pause = None
    return words


def texts(words: list[Word], params: JoinerParams = JoinerParams()) -> list[str]:
    return [sentence.text for sentence in join_words(words, params=params)]


def numbered(count: int, **replace: str) -> list[str]:
    """Unpunctuated tokens " w0" .. " w{count-1}", with ``w<k>=`` overrides."""
    tokens = [f" w{k}" for k in range(count)]
    for key, token in replace.items():
        tokens[int(key[1:])] = token
    return tokens


class ReconstructionTests(unittest.TestCase):
    def test_leading_space_concatenation(self):
        cases = [
            ([" thisamericanlife", ".org", " slash", " life"], "thisamericanlife.org slash life"),
            ([" call", " 800", "-273", "-TALK"], "call 800-273-TALK"),
            ([" ma", "'am", " said", " (well"], "ma'am said (well"),
        ]
        for tokens, expected in cases:
            with self.subTest(expected):
                self.assertEqual(texts(lay(*tokens)), [expected])

    def test_cjk(self):
        words = lay("今天", "天气", "很好。", "我们", "去", "公园", "吧？", "好")
        sentences = join_words(words)
        self.assertEqual([s.text for s in sentences], ["今天天气很好。", "我们去公园吧？", "好"])
        self.assertEqual([s.break_reason for s in sentences], ["punct", "punct", "eof"])

    def test_blank_words_are_skipped(self):
        words = [Word(0.0, 0.3, " Hi", 0.9, 0), Word(0.3, 0.3, " ", 0.1, 0), Word(0.3, 0.3, "", 0.1, 0)]
        words += lay(" there.", " Bye", " now.", start=0.32)
        sentences = join_words(words)
        self.assertEqual([s.text for s in sentences], ["Hi there.", "Bye now."])
        self.assertEqual([(s.word_start, s.word_count) for s in sentences], [(0, 4), (4, 2)])


class BoundaryTests(unittest.TestCase):
    # (label, tokens up to and including the "." word, next word)
    GUARDED = [
        ("G1 ellipsis", [" and", " I..."], " Okay"),
        ("G2 decimal", [" was", " 3."], "5"),
        ("G3 initial", [" John", " C."], " Stennis"),
        ("G3 lowercase initial", [" Roe", " v."], " Wade"),
        ("G4 initialism in four pieces", [" From", " W", ".B", ".E", ".Z."], " Chicago"),
        ("G5 title", [" met", " Dr."], " Fuchs"),
        ("G5 sentence-final abbreviation before lowercase", [" and", " so", " on,", " etc."], " so"),
        ("G5 sentence-final abbreviation before a digit", [" room", " No."], " 5"),
        ("G4/G5 p.m. before lowercase", [" 6", " p", ".m."], " at"),
        ("G6 domain before lowercase", [" at", " thisamericanlife", ".org."], " around"),
    ]
    # (label, tokens, next word): real boundaries even with no pause at all.
    SPLIT = [
        ("numbered-list marker", [" in", " 1995."], " Then"),
        ("no. before a capital", [" said", " no."], " I"),
        ("p.m. before a capital", [" 11", " p", ".m."], " She"),
        ("pronoun I", [" did", " I."], " I"),
        ("domain before a capital", [" thisamericanlife", ".org."], " Graham"),
        ("? before lowercase", [" these", " people?"], " as"),
        ("! is always terminal", [" Go,", " Wolfie!"], " Go"),
        ("closing quote", [" said,", ' "Stop."'], " He"),
        ("closing bracket", [" was", " (done.)"], " He"),
        ("CJK full stop", ["很", "好。"], "我们"),
    ]

    @staticmethod
    def token(tokens: list[str]) -> str:
        # The guards see the whitespace-delimited token, not the last ASR word.
        tail = []
        for piece in reversed(tokens):
            tail.insert(0, piece)
            if piece[:1].isspace():
                break
        return "".join(tail).strip()

    def test_guards_suppress_without_a_pause(self):
        for label, tokens, following in self.GUARDED:
            with self.subTest(label):
                self.assertFalse(is_sentence_end(self.token(tokens), following, 0.0))
                sentences = join_words(lay(*tokens, 0.0, following, " left."))
                self.assertEqual(len(sentences), 1, [s.text for s in sentences])

    def test_pause_overrides_every_guard(self):
        for label, tokens, following in self.GUARDED:
            with self.subTest(label):
                self.assertTrue(is_sentence_end(self.token(tokens), following, 0.8))
                sentences = join_words(lay(*tokens, 0.8, following, " left."))
                self.assertEqual(len(sentences), 2)
                self.assertEqual(sentences[0].text, "".join(tokens).strip())
                self.assertEqual(sentences[0].break_reason, "punct")

    def test_unguarded_terminals_split_without_a_pause(self):
        for label, tokens, following in self.SPLIT:
            with self.subTest(label):
                self.assertTrue(is_sentence_end(self.token(tokens), following, 0.0))
                sentences = join_words(lay(*tokens, 0.0, following, " left."))
                self.assertEqual([s.break_reason for s in sentences], ["punct", "eof"])
                self.assertEqual(sentences[0].text, "".join(tokens).strip())

    def test_decimal_stays_in_one_sentence(self):
        self.assertEqual(texts(lay(" It", " was", " 3.", "5", " percent.")), ["It was 3.5 percent."])

    def test_non_terminals(self):
        for token in ("word", "word,", "Hmm…", "", "(well"):
            with self.subTest(token):
                self.assertFalse(is_sentence_end(token, " next", 5.0))


class GapTests(unittest.TestCase):
    def test_pause_on_the_threshold_breaks(self):
        # 12.34 - 11.74 is 0.5999999999999996 in floats; at centisecond
        # resolution it is exactly the 0.60 s threshold.
        words = [Word(11.44, 11.74, " so", 0.9, 0), Word(12.34, 12.64, " then", 0.9, 0),
                 Word(12.66, 12.96, " left", 0.9, 0)]
        sentences = join_words(words)
        self.assertEqual([s.text for s in sentences], ["so", "then left"])
        self.assertEqual(sentences[0].break_reason, "gap")

    def test_shorter_pause_does_not_break(self):
        self.assertEqual(texts(lay(" so", 0.58, " then", " left")), ["so then left"])

    def test_merge_window_zeroes_jitter(self):
        params = JoinerParams(gap_hard=0.03)
        self.assertEqual(texts(lay(" so", 0.04, " then", 0.06, " left"), params), ["so then", "left"])


class CapTests(unittest.TestCase):
    def test_cap_cuts_at_the_widest_trailing_pause(self):
        # The 0.5 s pause after w10 is wider but outside the trailing 40%.
        tokens = numbered(60)
        items: list[str | float] = []
        for k, token in enumerate(tokens):
            items.append(token)
            items.extend({10: [0.5], 40: [0.3], 45: [0.4]}.get(k, []))
        sentences = join_words(lay(*items))
        self.assertEqual(len(sentences), 2)
        first, second = sentences
        self.assertTrue(first.text.endswith(" w45"))
        self.assertEqual((first.break_reason, first.soft_end), ("cap", True))
        self.assertEqual((first.word_start, first.word_count), (0, 46))
        self.assertTrue(second.text.startswith("w46"))
        self.assertEqual((second.break_reason, second.soft_end), ("eof", False))

    def test_cap_fallback_order(self):
        # 60 words 0.32 s apart cross 18 s at w56; the search covers w34..w56.
        cases = [
            ("soft punctuation", numbered(60, w50=" w50,"), [], 50),
            ("soft punctuation beats a later discourse marker", numbered(60, w50=" w50,", w53=" and"), [], 50),
            ("discourse marker: cut before it", numbered(60, w48=" and"), [], 47),
            ("'cause is a discourse marker", numbered(60, w52=" 'cause"), [], 51),
            ("a pause beats soft punctuation", numbered(60, w50=" w50,"), [40], 40),
            ("nothing to find: cut at the crossing word", numbered(60), [], 56),
            ("soft punctuation before the search window is ignored", numbered(60, w20=" w20,"), [], 56),
        ]
        for label, tokens, pause_after, cut in cases:
            with self.subTest(label):
                items: list[str | float] = []
                for k, token in enumerate(tokens):
                    items.append(token)
                    if k in pause_after:
                        items.append(0.3)
                first = join_words(lay(*items))[0]
                self.assertEqual((first.break_reason, first.word_count), ("cap", cut + 1))

    def test_every_soft_punctuation_mark(self):
        for mark in ",;:—、，":
            with self.subTest(mark):
                first = join_words(lay(*numbered(60, w50=f" w50{mark}")))[0]
                self.assertEqual(first.word_count, 51)

    def test_character_cap(self):
        words = lay(*(f" word{k:05d}" for k in range(40)), dur=0.10)
        first = join_words(words)[0]
        self.assertEqual(first.break_reason, "cap")
        self.assertEqual(len(first.text), 329)  # 33 ten-character words cross 320
        self.assertLess(first.end - first.start, 18.0)

    def test_long_span_flag(self):
        long_word = join_words([Word(0.0, 20.0, " way.", 0.9, 0), Word(20.5, 21.0, " Next.", 0.9, 0)])[0]
        self.assertIn("long_span", long_word.flags)
        exact = join_words([Word(0.0, 18.0, " way.", 0.9, 0), Word(18.5, 19.0, " Next.", 0.9, 0)])[0]
        self.assertNotIn("long_span", exact.flags)


class TimingAndProvenanceTests(unittest.TestCase):
    def test_cross_segment_merge(self):
        words = lay(" The", " cat", segment=0) + lay(" sat.", start=0.64, segment=1)
        (sentence,) = join_words(words)
        self.assertEqual(sentence.text, "The cat sat.")
        self.assertEqual(sentence.asr_segments, (0, 1))

    def test_non_monotonic_splice_is_clamped(self):
        words = [
            Word(0.50, 0.90, " We", 0.9, 0), Word(0.90, 1.50, " left.", 0.9, 0),
            Word(1.30, 1.80, " In", 0.9, 1),  # starts before "left." ends
            Word(1.80, 2.10, " time.", 0.9, 1),
            Word(5.00, 6.00, " Like...", 0.9, 1),
            Word(4.60, 5.40, " how", 0.9, 2),  # starts and ends inside the previous word
            Word(6.00, 6.40, " come.", 0.9, 2),
        ]
        sentences = join_words(words)
        self.assertEqual([(s.text, s.start, s.end) for s in sentences],
                         [("We left.", 0.5, 1.5), ("In time.", 1.5, 2.1), ("Like... how come.", 5.0, 6.4)])

    def test_short_punct_line_glues_forward(self):
        words = [Word(0.00, 0.12, " Uh.", 0.9, 0), Word(0.20, 0.60, " Yeah.", 0.9, 0), Word(0.70, 1.00, " So", 0.9, 0)]
        sentences = join_words(words)
        self.assertEqual([(s.text, s.break_reason) for s in sentences], [("Uh. Yeah.", "punct"), ("So", "eof")])

    def test_short_punct_line_before_a_pause_still_splits(self):
        words = [Word(0.00, 0.12, " Uh.", 0.9, 0), Word(0.92, 1.30, " Yeah.", 0.9, 0)]
        self.assertEqual([(s.text, s.break_reason) for s in join_words(words)], [("Uh.", "punct"), ("Yeah.", "eof")])

    def test_zero_duration_words(self):
        words = [Word(5.0, 5.0, " Top", 0.9, 0), Word(5.0, 5.0, " cat.", 0.9, 0),
                 Word(6.0, 6.3, " Next", 0.9, 0), Word(6.3, 6.6, " one.", 0.9, 0)]
        sentences = join_words(words)
        self.assertEqual([(s.text, s.start, s.end) for s in sentences], [("Top cat.", 5.0, 5.0), ("Next one.", 6.0, 6.6)])

    def test_empty_input(self):
        self.assertEqual(join_words([]), [])
        self.assertEqual(join_words(lay(" ", "")), [])


class FlagTests(unittest.TestCase):
    def test_repeat_thresholds(self):
        cases = [  # (n-gram, copies, flagged)
            (["ooh"], 5, False), (["ooh"], 6, True),
            (["go", "wolfie"], 3, False), (["go", "wolfie"], 4, True),
            (["top", "cat", "bali"], 3, False), (["top", "cat", "bali"], 4, True),
            (["i", "don't", "know", "why"], 3, False), (["i", "don't", "know", "why"], 4, True),
        ]
        for gram, copies, flagged in cases:
            with self.subTest(gram=gram, copies=copies):
                tokens = [" We", " heard"] + [f" {t}," for t in gram] * copies + [" and", " left."]
                (sentence,) = join_words(lay(*tokens))
                self.assertEqual("repetitive" in sentence.flags, flagged)

    def test_repeat_run_spanning_short_lines_flags_each(self):
        words = lay(" Thank", " you.", " Thank", " you.", " Thank", " you.", " Thank", " you.", " Then", " quiet.")
        sentences = join_words(words)
        self.assertEqual([("repetitive" in s.flags) for s in sentences], [True, True, True, True, False])

    def test_repeat_runs_spans(self):
        self.assertEqual(repeat_runs("x a a a a a a y".split(), 1, 6), [(1, 7)])
        self.assertEqual(repeat_runs("x a a a a a y".split(), 1, 6), [])
        self.assertEqual(repeat_runs("a b a b a b a b a".split(), 2, 4), [(0, 9)])  # trailing partial copy kept
        self.assertEqual(repeat_runs([], 2, 4), [])

    def test_confidence_thresholds(self):
        cases = [  # (word probabilities, params, flagged)
            ([0.54, 0.56], JoinerParams(), False),  # mean exactly 0.55
            ([0.54, 0.55], JoinerParams(), True),  # mean 0.545
            ([0.10, 0.99, 0.99], JoinerParams(), False),  # min exactly 0.10
            ([0.09, 0.99, 0.99], JoinerParams(), True),
            ([0.30, 0.99, 0.99], JoinerParams(low_conf_min_p=0.30), False),
            ([0.29, 0.99, 0.99], JoinerParams(low_conf_min_p=0.30), True),
        ]
        for probabilities, params, flagged in cases:
            with self.subTest(probabilities=probabilities, min_p=params.low_conf_min_p):
                words = [Word(0.3 * k, 0.3 * k + 0.28, f" w{k}", p, 0) for k, p in enumerate(probabilities)]
                (sentence,) = join_words(words, params=params)
                self.assertEqual("low_confidence" in sentence.flags, flagged)
                self.assertEqual(sentence.min_p, min(probabilities))

    def test_high_compression(self):
        words = lay(" Top", " cat.", segment=3)
        for ratio, flagged in ((2.41, True), (2.40, False)):
            with self.subTest(ratio=ratio):
                segments = [AsrSegmentMeta(3, 0.0, 1.0, ratio, 0.1, -0.2)]
                (sentence,) = join_words(words, segments)
                self.assertEqual("high_compression" in sentence.flags, flagged)
        self.assertEqual(join_words(words)[0].flags, ())  # no metadata, no flag


class SilenceTests(unittest.TestCase):
    WORDS = [Word(3.5, 4.0, " a", 0.9, 0), Word(4.1, 4.5, " b", 0.9, 0), Word(7.5, 8.0, " c", 0.9, 0),
             Word(8.1, 8.4, " d", 0.9, 0), Word(11.39, 11.7, " e", 0.9, 0)]

    def test_head_gaps_and_short_tail(self):
        self.assertEqual(derive_silences(self.WORDS, 12.0), [
            SilenceRegion(0.0, 3.5, "head"),
            SilenceRegion(4.5, 7.5, "gap"),  # exactly silence_min_s; the 2.99 s gap is not
            SilenceRegion(11.7, 12.0, "tail"),  # always reported, however short
        ])

    def test_tail_needs_a_longer_known_duration(self):
        for duration in (None, 11.7, 11.0):
            with self.subTest(duration=duration):
                self.assertEqual([r.kind for r in derive_silences(self.WORDS, duration)], ["head", "gap"])

    def test_short_head_is_not_silence(self):
        words = [Word(2.99, 3.2, " a", 0.9, 0)]
        self.assertEqual(derive_silences(words, 3.2), [])

    def test_gap_starts_after_the_longest_word(self):
        words = [Word(0.0, 10.0, " way", 0.9, 0), Word(1.0, 2.0, " in", 0.9, 1), Word(15.0, 15.5, " out", 0.9, 1)]
        self.assertEqual(derive_silences(words, None), [SilenceRegion(10.0, 15.0, "gap")])

    def test_no_words(self):
        self.assertEqual(derive_silences([], None), [])
        self.assertEqual(derive_silences([], 0.0), [])
        self.assertEqual(derive_silences([], 12.5), [SilenceRegion(0.0, 12.5, "tail")])


class GoldenFixtureTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.fixture, cls.words, cls.segments = load_fixture()
        cls.sentences = join_words(cls.words, cls.segments)
        cls.silences = derive_silences(cls.words, cls.fixture["cut_seconds"])

    def test_fixture_provenance(self):
        source = self.fixture["source"]
        self.assertEqual(source["sha256"], "17888b354c3e91ebde25dcac7520f824f0ad485bd7717e319cc80c2a1d043109")
        self.assertEqual(source["episode"]["audio_sha256"],
                         "b9489445cc15440d12d9e4398d16d1f9b91e63f6e2e7c6901c2a0bc68bdd3235")
        self.assertEqual((source["asr"]["model"], source["asr"]["model_sha256"]),
                         ("Systran/faster-whisper-tiny.en",
                          "1a5afae06a4db91c975c9a9d78be5cc110ee4ea022ad57d55492e4550e936b2a"))
        self.assertTrue(source["asr"]["word_timestamps"])
        self.assertEqual((len(self.words), len(self.segments)), (1621, 19))

    def test_sentence_count_and_reasons(self):
        self.assertEqual(len(self.sentences), 156)
        reasons = [s.break_reason for s in self.sentences]
        self.assertEqual({r: reasons.count(r) for r in set(reasons)}, {"punct": 142, "gap": 13, "eof": 1})

    def test_first_and_last_sentences(self):
        rows = [(s.text, s.start, s.end, s.break_reason) for s in self.sentences]
        self.assertEqual(rows[:5], [
            ("A quick warning, there are curse words that are un beeped in today's episode of the show.",
             0.69, 5.05, "punct"),
            ("If you prefer a beeped version, you can find that at our website, thisamericanlife.org.",
             5.49, 10.73, "punct"),
            ("Graham grew up in a working class town north of England.", 12.03, 14.69, "punct"),
            ("And when he was 11 or 12, his family moved into one of the first houses in a new development "
             "that was being built and was kind of hitting the jackpot for him at that age.", 15.65, 22.51, "punct"),
            ("Because all around, everywhere were homes under construction,", 23.05, 25.59, "gap"),
        ])
        self.assertEqual(rows[-5:], [
            ("We", 576.96, 577.48, "gap"),
            ("burn knock chomp at incense and cracked ourselves up about things we called social experiments.",
             578.73, 583.49, "punct"),
            ("These were basically fantasies about ways we could be completely inappropriate in situations "
             "where certain contained behavior was expected.", 584.37, 590.31, "punct"),
            ("Like the public library.", 591.01, 591.97, "punct"),
            ("That's", 599.9, 600.12, "eof"),
        ])

    def test_silences(self):
        # 353.09 -> 373.76 is the music bed that VAD counts as speech.
        self.assertEqual([(r.start, r.end, r.kind) for r in self.silences], [
            (240.38, 246.96, "gap"), (353.09, 373.76, "gap"), (485.08, 497.12, "gap"),
            (555.77, 560.86, "gap"), (567.84, 576.96, "gap"), (591.97, 599.9, "gap"),
        ])

    def test_invariants(self):
        sentences = self.sentences
        self.assertEqual([s.index for s in sentences], list(range(len(sentences))))
        for before, after in zip(sentences, sentences[1:]):
            self.assertLessEqual(before.start, before.end)
            self.assertLessEqual(before.end, after.start)
        covered = [i for s in sentences for i in range(s.word_start, s.word_start + s.word_count)]
        self.assertEqual(covered, list(range(len(self.words))))  # every word in exactly one sentence, in order
        joined = "".join(s.text for s in sentences)
        self.assertEqual("".join(joined.split()), "".join("".join(w.word for w in self.words).split()))
        for region in self.silences:
            for sentence in sentences:
                self.assertTrue(region.end <= sentence.start or region.start >= sentence.end, (region, sentence))
        self.assertTrue(any(len(s.asr_segments) > 1 for s in sentences))  # the stream crosses VAD chunks

    def test_rejoin_from_codec_is_exact(self):
        words = decode_words(encode_words(self.words))
        segments = decode_segments(encode_segments(self.segments))
        self.assertEqual(join_words(words, segments), self.sentences)
        self.assertEqual(derive_silences(words, self.fixture["cut_seconds"]), self.silences)


if __name__ == "__main__":
    unittest.main()
